title: # #
logo: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fes.pinterest.com%2Fmanmargim1509%2Fla-que-se-avecina%2F&psig=AOvVaw2pQ70SOfMBTJKUHu1ue_qx&ust=1729594275021000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPjOtfamn4kDFQAAAAAdAAAAABAm"
theme: just-the-docs

url: https://lopgonhug.github.io
   
nav_external_links:
  - title: intro
    url: https://youtu.be/vJx2R2YuYl8?si=pjTYyrNcixZCatIg
    hide_icon: false
    opens_in_new_tab: true
