title: La que se avecina
description: hola
theme: just-the-docs

url: https://lopgonhug.github.io

 nav_external_links:
  - title: intro
    url: https://youtu.be/iDXF8nPwlKI?si=JQ5p93V_O-8IwWIE
    hide_icon: false
    opens_in_new_tab: true
