title: La que se avecina
theme: just-the-docs

url: https://lopgonhug.github.io


 nav_external_links:
  - title: intro
    url: https://www.youtube.com/watch?v=sM4kjx_6nkE
    hide_icon: false
    opens_in_new_tab: true
